# Generated by Django 4.1.7 on 2023-02-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="criados",
            field=models.DateField(auto_now_add=True, verbose_name="Criação"),
        ),
        migrations.AlterField(
            model_name="servico",
            name="criados",
            field=models.DateField(auto_now_add=True, verbose_name="Criação"),
        ),
        migrations.AlterField(
            model_name="time",
            name="criados",
            field=models.DateField(auto_now_add=True, verbose_name="Criação"),
        ),
    ]
